name: ğŸš€ Implantar site por push
on:
  push:
    branches:
       - main
        

jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Obtenha o codigo mais recente
      uses: actions/checkout@v3
    
    - name: ğŸ“‚ Sincronizar arquivos
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        port: ${{ secrets.FTP_PORT }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/
        local-dir: ./ # DiretÃ³rio local que serÃ¡ sincronizado





        name: ğŸš€ Implantar site por push
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Obtenha o cÃ³digo mais recente
        uses: actions/checkout@v3

      - name: ğŸ” Configurar FTP
        run: |
          sudo apt-get install -y lftp

      - name: ğŸ“‚ Sincronizar arquivos
        run: |
          lftp -u "${{ secrets.FTP_USER }}","${{ secrets.FTP_PASSWORD }}" -e "mirror -R --only-newer --delete ./ /public_html/; quit" ${{ secrets.FTP_HOST }}

