name: 游 Implantar site por push
on:
  push:
    branches:
      - main  # Branch monitorado para deploy

jobs:
  web-deploy:
    name: 游꿀 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 游뚴 Obtenha o c칩digo mais recente
      uses: actions/checkout@v3
    
    - name: 游늭 Sincronizar arquivos modificados
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        port: ${{ secrets.FTP_PORT }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/  # Diret칩rio remoto na Hostinger
        local-dir: ./  # Diret칩rio local que ser치 sincronizado
        method: sync  # Faz o deploy apenas dos arquivos modificados
        exclude: |
          **/.git*
          **/node_modules/**
          **/build/**  # Se quiser excluir pastas espec칤ficas
